// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://orctxxpyiqzbordibqxi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9yY3R4eHB5aXF6Ym9yZGlicXhpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5MzE5MTUsImV4cCI6MjA3MzUwNzkxNX0.DBfz7Ho3QebEgOwjXh8ciWD83jOT_bgVIl7uVknv4D4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});